# Generated by Django 6.0.6 on 2026-06-19 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story_title', models.CharField(max_length=200)),
                ('story_paragraph_1', models.TextField()),
                ('story_paragraph_2', models.TextField()),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='cms/about/')),
                ('mission_text', models.TextField()),
                ('vision_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='cms/team/')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide icon name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
            },
        ),
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heritage_subtitle', models.CharField(default='Our Heritage', max_length=200)),
                ('heritage_title', models.CharField(default='A Sanctuary of Soul and Elegance', max_length=200)),
                ('heritage_paragraph_1', models.TextField()),
                ('heritage_paragraph_2', models.TextField()),
                ('stat_1_number', models.CharField(max_length=50)),
                ('stat_1_label', models.CharField(max_length=100)),
                ('stat_2_number', models.CharField(max_length=50)),
                ('stat_2_label', models.CharField(max_length=100)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='cms/homepage/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='cms/homepage/')),
            ],
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g. Compass, Sparkles, Award)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Hotel Amenities',
            },
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='cms.gallerycategory'),
        ),
    ]
